apiVersion: apps/v1
kind: Deployment
metadata:
  name: davidsauthtestcg8zajs7-main
spec:
  selector:
    matchLabels:
      app: davidsauthtestcg8zajs7-main
  template:
    metadata:
      labels:
        app: davidsauthtestcg8zajs7-main
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: davidsauthtestcg8zajs7-main
          image: uiflowazureregistry.azurecr.io/davidsauthtestcg8zajs7-main
          command: ['node', 'server.js', 'davidsauthtestcg8zajs7-main-vault', 'ehQZs68/LPFcB75wdh+AafAqGJeg+pMc6U2Bt4ggpnAS4hMvtFbCq+FY1X5CIcRADlNGo9/GDUHdUl1oyLceSwGYZgCr8PujWLclqW8UzM7yvla46fc+szLwDZk=', 'fpoqi2brbbvKwiCTTV1Sm/IYb5XAcyD/Ky1Q09Kz9u4fX+p8K01ydf8rTIBwx9HoIMhvQNCyUTI=']
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        - name: davidsauthtestcg8zajs7-main-vault
          image: uiflowazureregistry.azurecr.io/davidsauthtestcg8zajs7-main-vault
          command: ['vault', 'server', '-config=/vault/config/vault-config.json']
          env:
            - name: VAULT_ADDR
              value: 'http://127.0.0.1:8200'
            - name: VAULT_DISABLE_MLOCK
              value: 'true'
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: davidsauthtestcg8zajs7-main
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: davidsauthtestcg8zajs7-main
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: davidsauthtestcg8zajs7-main
