apiVersion: apps/v1
kind: Deployment
metadata:
  name: $uiflow_image
spec:
  selector:
    matchLabels:
      app: $uiflow_image
  template:
    metadata:
      labels:
        app: $uiflow_image
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: $uiflow_image
          image: $azure_acr/$uiflow_image
          command: ['node', 'server.js', '$vault_image', '$unseal_key', '$token']
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
        - name: $vault_image
          image: $azure_acr/$vault_image
          command: ['vault', 'server', '-config=/vault/config/vault-config.json']
          env:
            - name: VAULT_ADDR
              value: 'http://127.0.0.1:8200'
            - name: VAULT_DISABLE_MLOCK
              value: 'true'
          ports:
            - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: $uiflow_image
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: $uiflow_image
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: $uiflow_image
